# Generated by Django 5.2.4 on 2025-07-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='-', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
